spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/ssafydb
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # security:
  #   user: ssafy
  #   password: ssafy

logging.level:
  org.hibernate.SQL: debug
