spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/ssafydb
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
