spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/ssafydb
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      accessKey: AKIATD5L7CMI2SALOZHB
      secretKey: 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
    s3:
      bucket: ssafy-bucket
    region:
      static: us-east-2
    stack:
      auto: false
